title: ASAPAdventures
baseurl: ''
url: 'http://www.asapadventures.com'
author: 'Amy Sellitti'

markdown: kramdown
relative_permalinks: false
permalink: :title/
plugins:
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed

collections:
  travel-guides:
    output: true
    permalink: /travelguides/:path

  guide-japan:
    output: true
    permalink: /travelguides/japan/:path

  guide-malaysia:
    output: true
    permalink: /travelguides/malaysia/:path

  travel-blog:
    output: true
    permalink: /travelblog/:path

  blog-2010-japan:
    output: true
    permalink: /travelblog/2010japan/:path/

  blog-2012-singapore-malaysia:
    output: true
    permalink: /travelblog/2012singaporemalaysia/:path/

  blog-2013-adelaide:
    output: true
    permalink: /travelblog/2013adelaide/:path/

  blog-2014-hong-kong:
    output: true
    permalink: /travelblog/2014hongkong/:path/

  blog-2015-new-zealand:
    output: true
    permalink: /travelblog/2015newzealand/:path/

  blog-2016-taiwan-japan:
    output: true
    permalink: /travelblog/2016taiwanjapan/:path/

  blog-2017-new-zealand:
    output: true
    permalink: /travelblog/2017newzealand/:path/

  blog-2017-hong-kong:
    output: true
    permalink: /travelblog/2017hongkong/:path

  blog-2018-singapore-hong-kong:
    output: true
    permalink: /travelblog/2018singaporehongkong/:path/

  blog-2018-japan:
    output: true
    permalink: /travelblog/2018japan/:path/

  blog-2019-canberra:
    output: true
    permalink: /travelblog/2019canberra/:path/