title: ASAPAdventures
baseurl: ''
url: 'https://www.asapadventures.com'
author: 'Amy Sellitti'

markdown: kramdown
relative_permalinks: false
permalink: :title/
plugins:
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - script

collections:
  travel-guides:
    output: true
    permalink: /travelguides/:path

  guide-japan:
    output: true
    permalink: /travelguides/japan/:path

  guide-malaysia:
    output: true
    permalink: /travelguides/malaysia/:path

  guide-australia:
    output: true
    permalink: /travelguides/australia/:path

  travel-blog:
    output: true
    permalink: /travelblog/:path

  blog-2010-japan:
    output: true
    permalink: /travelblog/2010japan/:path/

  blog-2012-singapore-malaysia:
    output: true
    permalink: /travelblog/2012singaporemalaysia/:path/

  blog-2013-adelaide:
    output: true
    permalink: /travelblog/2013adelaide/:path/

  blog-2014-hong-kong:
    output: true
    permalink: /travelblog/2014hongkong/:path/

  blog-2015-new-zealand:
    output: true
    permalink: /travelblog/2015newzealand/:path/

  blog-2016-taiwan-japan:
    output: true
    permalink: /travelblog/2016taiwanjapan/:path/

  blog-2017-new-zealand:
    output: true
    permalink: /travelblog/2017newzealand/:path/

  blog-2017-hong-kong:
    output: true
    permalink: /travelblog/2017hongkong/:path

  blog-2018-singapore-hong-kong:
    output: true
    permalink: /travelblog/2018singaporehongkong/:path/

  blog-2018-japan:
    output: true
    permalink: /travelblog/2018japan/:path/

  blog-2019-canberra:
    output: true
    permalink: /travelblog/2019canberra/:path/

  blog-2019-korea-japan:
    output: true
    permalink: /travelblog/2019koreajapan/:path/

  blog-2019-vietnam-taiwan:
    output: true
    permalink: /travelblog/2019vietnamtaiwan/:path/

  blog-2020-canberra:
    output: true
    permalink: /travelblog/2020canberra/:path/

  blog-2021-outback-nsw:
    output: true
    permalink: /travelblog/2021outbacknsw/:path/

  blog-2021-the-top-end:
    output: true
    permalink: /travelblog/2021thetopend/:path/

  blog-2020-queensland:
    output: true
    permalink: /travelblog/2020queensland/:path/

  blog-2020-south-australia:
    output: true
    permalink: /travelblog/2020southaustralia/:path/

  blog-2020-tasmania:
    output: true
    permalink: /travelblog/2020tasmania/:path/

#  blog-2020-victoria:
#    output: true
#    permalink: /travelblog/2020victoria/:path/

  blog-2020-western-australia:
    output: true
    permalink: /travelblog/2020westernaustralia/:path/

  blog-2022-sunshine-coast:
    output: true
    permalink: /travelblog/2022sunshinecoast/:path/

  blog-2022-tasmania:
    output: true
    permalink: /travelblog/2022tasmania/:path/

  blog-2022-the-red-centre:
    output: true
    permalink: /travelblog/2022theredcentre/:path/

  blog-2023-the-fraser-coast:
    output: true
    permalink: /travelblog/2023thefrasercoast/:path/

  blog-2023-the-limestone-coast:
    output: true
    permalink: /travelblog/2023thelimestonecoast/:path/

  blog-2023-tasmania:
    output: true
    permalink: /travelblog/2023tasmania/:path/

  blog-2023-disney-cruise:
    output: true
    permalink: /travelblog/2023disney-cruise/:path/

  blog-2023-philippines-japan:
    output: true
    permalink: /travelblog/2023philippinesjapan/:path/

  # blog-2024-canberra:
  #   output: true
  #   permalink: /travelblog/2024canberra:path/

  blog-2024-southislandnz:
    output: true
    permalink: /travelblog/2024southislandnz:path/

  blog-2024-southeastasia:
    output: true
    permalink: /travelblog/2024eastasia:path/