# Site settings
title: ASAPAdventures

baseurl: ''
url: 'http://asapadventures.com'

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: :title/
gems: [jekyll-paginate]

pagination: true
paginate: 8
paginate_path: page/:num/

sass:
  sass_dir: _sass
  style: compressed

collections:
  japan2010:
    output: true
    permalink: /japan2010/:path/

  singaporemalaysia2012:
    output: true
    permalink: /singaporemalaysia2012/:path/

  adelaide2013:
    output: true
    permalink: /adelaide2013/:path/

  hongkong2014:
    output: true
    permalink: /hongkong2014/:path/

  newzealand2015:
    output: true
    permalink: /newzealand2015/:path/

  taiwanjapan2016:
    output: true
    permalink: /taiwanjapan2016/:path/

  newzealand2017:
    output: true
    permalink: /newzealand2017/:path/

  hongkong2017:
    output: true
    permalink: /hongkong2017/:path/
